services:
  web:
    environment:
      - PHPVERSION
    build:
      context: .
      args:
        - PHPVERSION=${PHPVERSION}
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:80

  db:
    image: mariadb:11.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    ports:
      - 127.0.0.1:3306:3306
