name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        wordpress-version: [ '6.0', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7' ]
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker compose up -d
          sleep 30
          docker compose run web sh -c "php -v"
          docker compose run web sh -c "/vendor/bin/phpcs -i"
          docker compose run web sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"
          docker compose run web sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp root PASSWORD db ${{ matrix.wordpress-version }} && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"
