name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test (PHP ${{ matrix.php-version }} and WordPress ${{ matrix.wordpress-version }})
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
        wordpress-version: [ '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Test
        shell: bash
        run: |
          docker compose build --build-arg PHPVERSION="${{ matrix.php-version }}"
          docker compose up -d
          sleep 30
          docker compose run web sh -c "php -v"
          docker compose run web sh -c "/vendor/bin/phpcs -i"
          docker compose run web sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"
          docker compose run web sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp root PASSWORD db ${{ matrix.wordpress-version }} && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"
