name: build

on:
  push:
    branches:
      - "*"

jobs:
  test-with-wordpress67:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50067:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp67 root PASSWORD localhost 6.7 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"


  test-with-wordpress66:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50066:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp66 root PASSWORD localhost 6.6 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress65:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50065:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp65 root PASSWORD localhost 6.5 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50064:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp64 root PASSWORD localhost 6.4 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress63:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50063:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp63 root PASSWORD localhost 6.3 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress62:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50062:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp62 root PASSWORD localhost 6.2 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress61:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50061:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp61 root PASSWORD localhost 6.1 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress60:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50060:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp60 root PASSWORD localhost 6.0 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress59:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50059:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp59 root PASSWORD localhost 5.9 && /vendor/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress58:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50058:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "rm -f /usr/local/bin/phpunit && curl -L -o /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-7.phar && chmod +x /usr/local/bin/phpunit && /usr/local/bin/phpunit --version"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp58 root PASSWORD localhost 5.8 && /usr/local/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"

  test-with-wordpress57:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-run
        shell: bash
        run: |
          docker build -t fmpress-ubuntu .
          docker run -d --name testcontainer --rm -p 50057:80 fmpress-ubuntu

          docker exec -i testcontainer sh -c "php -v"
          docker exec -i testcontainer sh -c "/vendor/bin/phpcs -i"

          docker exec -i testcontainer sh -c "/vendor/bin/phpcs --standard=/fmpress-forms/phpcs.xml --extensions=php /fmpress-forms"

          docker exec -i testcontainer sh -c "/etc/init.d/mysql start &"

          docker exec -i testcontainer sh -c "rm -f /usr/local/bin/phpunit && curl -L -o /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-7.phar && chmod +x /usr/local/bin/phpunit && /usr/local/bin/phpunit --version"

          docker exec -i testcontainer sh -c "cd /var/www/html/wp-content/plugins/fmpress-forms && ./bin/install-wp-tests.sh wp57 root PASSWORD localhost 5.7 && /usr/local/bin/phpunit --bootstrap=tests/phpunit/bootstrap.php tests/phpunit/fmpress-forms-test.php"
